### PR TITLE
commit to review

### PR DESCRIPTION
**Pull request by ahmedtaa**
# in this branch

- Changed the document title

### CODE REVIEW

**Review by Cathella — CHANGES_REQUESTED** [review]
## Status: Changes Required 🛑

### Hi @ahmedtaa ✋🏻, 

Good job so far!

There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## The Good points 👏🏻

✅ No linter errors.
✅ Proper GitHub flow
✅ Project has a good page structure and Navigation


## Required Changes ♻️
_Check the comments under the review._

- [x] [REQUIRED] The capstone project requires recorded 5 minutes loom video presenting the features of the project. I highly recommend that you record it and please provide a link in the `README` file or pull request.
- [x] [REQUIRED] I also kindly request  that you update the project `README` file 🧾  to reflect information about your capstone project. `README's` help a user to know more about your project, how you developed it, its concept and how to use it. You can use a [Microverse `README` template](https://github.com/Hope1226/Microverse-README-template) to make yours look professional.
- [x] [REQUIRED] Please make use of GitHub Pages to deploy the capstone project online and also add a link of the deployed project in the README.

### Footer
- [x] [REQUIRED] The Footer - (Mobile Size) is meant to have a white background while the (Desktop Size) is meant to have dark background. I request that you implement this with the help of media-queries

| Desktop footer | Mobile footer |
| --- | --- |
| image | image |

### Homepage

- [x] [REQUIRED] In the top section, I kindly suggest that you add a background image with a fade effect as seen in the recommended design to make sure that your project design is a close as possible or exact to the required design.

| Your design | Required design |
| --- | --- |
| image | image |

- [x] In the popular clubs section, I kindly suggest that your design matches the one below. Points to work on include adjusting the padding, I would also recommend using `article` tags  instead of `li` tags.

image

- [x] [REQUIRED] The speakers are dynamically added, however, I think it would be nice if our speakers were unique. I there fore recommend creating 6 objects in a speakers array that you can loop through and render in the speaker's section.
```
const speakerList = [ 
  {
    name: "Julia Leda", 
    role: "President of Young pirates of Europe", 
    description: "European ingetration, political democracy, and participation of ...", 
    photo: "image_url_here"
  },
]
```

- [x] [REQUIRED] I also request that your featured speakers section matches the required design. This helps with keeping the website design consistent

| Your design | Required design |
| --- | --- |
| image | image |


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ahmedtaa** [comment]
Hi @Cathella 
Thanks for your help,

>  [REQUIRED] Please make use of GitHub Pages to deploy the capstone project online and also add a link to the deployed project in the README.

for this required issue, I just reviewed the requirements and it was not there, also if this is a requirement for you, would you please tell me how to do it? because when I did that live site two weeks earlier I made it in a new repo with my username, I also google it and didn't find another way.

**Comment by Cathella** [comment]
> Hi @Cathella Thanks for your help,
> 
> > [REQUIRED] Please make use of GitHub Pages to deploy the capstone project online and also add a link to the deployed project in the README.
> 
> for this required issue, I just reviewed the requirements and it was not there, also if this is a requirement for you, would you please tell me how to do it? because when I did that live site two weeks earlier I made it in a new repo with my username, I also google it and didn't find another way.

Hi @ahmedtaa , yes it is part of the project requirements as seen below 👇🏻 

image

**Comment by Cathella** [comment]
Yes please, I would love to show you how it is done if you are free to get on a call

**Review by rotimiazeez — APPROVED** [review]
# Hi @ahmedtaa 👍, 

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
